language: node_js
node_js: lts/*
cache: yarn

install:
  - yarn install --pure-lockfile

jobs:
  include:
    - stage: test-types
      script: yarn test:types
    - stage: deploy
      if: type = push AND branch = master
      script:
        - echo $NPM_TOKEN
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - yarn release --preRelease=rc
